### ISSUE TITLE
Issue on calculation of Prandtl number with incompressible MPG2

### ISSUE THREAD

**Issue by rviekr** [CoolProp/CoolProp#1374]
Hello everybody,
Using Excel I found that the Prandtl number calculated by incompressible MPG2 is divided by 10.

The syntax I used, has been:
=PropsSI("PRANDTL";"T";283,15;"P";101325;"INCOMP::MPG2[0.5]")   =>  Pr=10.409 (wrong value, I can correct, multiplicand it by 10)
instead if I calculate the number of Prandtl in the same condition with incompressible MPG I obtain:
=PropsSI("PRANDTL";"T";283,15;"P";101325;"INCOMP::MPG[0.5]")     =>  Pr=104.17 (right value)

Has anyone found that issue, or it is a my mistake?
Many thanks

**Comment by ibell** [comment]
@jowr - does this need to be fixed?

What version of CoolProp do you use?

**Comment by rviekr** [comment]
I'm using CoolProp for Windows 6.1

**Comment by jowr** [comment]
Yes, this should be fixed. @rviekr, can you figure out which part of the Prandtl number calculation is off? When you calculate the Prandtl number yourself, which values differ (MPG2 vs. MPG)?

**Comment by rviekr** [comment]
The differ value is on MPG2.
I tried to do the calculation of Prandtl using its definition, and I found the same wrong result. It seems the issue is on the dynamic viscosity (output key: "V") because it is 10 times smaller (same ratio I found on Prandtl) than the dynamic viscosity calculated by MPG and all other incompressible fluids based on propylene glycol (APG, AL).

**Comment by ibell** [comment]
@rviekr Have you tried the updated binaries from the nightly build?

**Comment by rviekr** [comment]
Yes, I reinstalled the binary downloaded from nightly built, but the issue remain.
